### PR TITLE
removed extra duplicate step at the end

### PR DESCRIPTION
**Pull request by nh916**
# Description
removed extra duplicate step at the end

## Checklist

- [ ] My name is on the list of contributors (`CONTRIBUTORS.md`) in the pull request source branch.
- [ ] I have updated the documentation to reflect my changes.

### CODE REVIEW

**Review by InnocentBug — APPROVED** [review]

**Comment by InnocentBug** [comment]
is there an option to error on a warning when we build the docs?
if yes, we might want to enable that for testing.

**Comment by nh916** [comment]
> is there an option to error on a warning when we build the docs? if yes, we might want to enable that for testing.

yeah the option would be 

```shell
mkdocs build --strict
```

however, when I first enabled it I was getting errors all the time and did not have time to fix them so I removed it for now. Some of the warnings that it is giving I am not sure how to fix

**Comment by InnocentBug** [comment]
That's fair, something to put on the post release to-do list

**Comment by nh916** [comment]
> That's fair, something to put on the post release to-do list

https://trello.com/c/al79B7wH

**Pull request merged**
