### PR TITLE
file upload feature

### PR DESCRIPTION
**Pull request by nh916**
# Description
feature to upload file to AWS S3 from SDK

## Changes
* added `boto3` to `requirements.txt`
* created `API.upload_file()` method
* 

## Tests
* 

## Known Issues
* not sure if the `url_expire_time` is too long or too short
* 

## Notes
* big thanks to @fatjon95 for helping me with the creation of this method! 🎉 

## Checklist

- [ ] My name is on the list of contributors (`CONTRIBUTORS.md`) in the pull request source branch.

### CODE REVIEW

**Comment by nh916** [comment]
@InnocentBug from what I understand I believe there would need to be a different token for file uploads, but this might also be just us in development stage and it might change going forward, not sure.

I think if we end up with 2 tokens we could possibly do something like 

```python
api = cript.API(host="https://criptapp,org", api_token="my api token", file_upload_token="my Globus/S3 token")
```

**Comment by InnocentBug** [comment]
> @InnocentBug from what I understand I believe there would need to be a different token for file uploads, but this might also be just us in development stage and it might change going forward, not sure.
> 
> I think if we end up with 2 tokens we could possibly do something like
> 
> ```python
> api = cript.API(host="https://criptapp,org", api_token="my api token", file_upload_token="my Globus/S3 token")
> ```

I see that makes sense.
Ideally we get the second token from CRIPT during the handshake.

I.e. the back end stores the the file_upload_token.
And when we create the API object we get that token from the back end (authenticated with the CRIPT TOKEN).

But temporary for development this might be fine.

**Comment by nh916** [comment]
for file upload my first idea is this, but not sure about the flow of it honestly. Let me know what you think

```python
import cript

with cript.API(host=None, token=None) as api:
    # upload and get back an S3 file link
    uploaded_file_source: str = api.upload_file(absolute_file_path="C:\\users\\username\\onedrive\\desktop\\my_file.txt")

    # use S3 file link
    my_file = cript.File(source=uploaded_file_source, type="my file type")

    # continue with the rest as usual
    my_data_node = cript.Data(name="my data node", file=[my_file], type="my data type")
```

 in the JSON it will have the file source written as
```json
{
    "node": ["file"],
    "name": "my file name",
    "type": "my file type",
    "source": "https://aws.123456.s3.link.come",
    "extension": ".csv"
}
``` 

> Note: I think in the future we can also add relative file paths as well but I did not add it here because I've noticed in the past that `../../my_file.txt` is not from where the file is, but from where the program has been ran which introduces another complication, but I think eventually I think we can make it work.

**Comment by InnocentBug** [comment]
> for file upload my first idea is this, but not sure about the flow of it honestly. Let me know what you think
> 
> ```python
> import cript
> 
> with cript.API(host=None, token=None) as api:
>     # upload and get back an S3 file link
>     uploaded_file_source: str = api.upload_file(absolute_file_path="C:\\users\\username\\onedrive\\desktop\\my_file.txt")
> 
>     # use S3 file link
>     my_file = cript.File(source=uploaded_file_source, type="my file type")
> 
>     # continue with the rest as usual
>     my_data_node = cript.Data(name="my data node", file=[my_file], type="my data type")
> ```
> 
> in the JSON it will have the file source written as
> 
> ```json
> {
>     "node": ["file"],
>     "name": "my file name",
>     "type": "my file type",
>     "source": "https://aws.123456.s3.link.come",
>     "extension": ".csv"
> }
> ```
> 
> > Note: I think in the future we can also add relative file paths as well but I did not add it here because I've noticed in the past that `../../my_file.txt` is not from where the file is, but from where the program has been ran which introduces another complication, but I think eventually I think we can make it work.

I think we should capsulate that a little better for the user.
The user should write something like this:
```python
import cript

with cript.API(host=None, token=None) as api:
    my_file = cript.File(absolute_file_path="C:\\users\\username\\onedrive\\desktop\\my_file.txt", type="my file type")

    # continue with the rest as usual
    my_data_node = cript.Data(name="my data node", file=[my_file], type="my data type")
 ```
And upon the first time the node is converted into json, we trigger a function within the file node.
So we overload the `get_json` function of file like this.
```python
class File:
   def get_json(self):
       if self.absolute_file_path is not None: # File hasn't been uploaded
               # upload and get back an S3 file link
               api = _get_cached_global_api()
               uploaded_file_source: str = api._upload_file(self.absolute_file_path)
               # Error checking
               self._json_attrs = replace(self._json_attrs, source = uploaded_file_source) # store the source for json serialization
               self.absolute_file_path = None # Signal that file has been successfully uploaded
       # Call parent `get_json` for actual serialization
       return super().get_json(self) 
```    
and set the `source` in `json_attr`.
Should be pretty simple to do. And hides all the complications from the user.
And this automatically keeps track to only do this once.

**Comment by nh916** [comment]
> > for file upload my first idea is this, but not sure about the flow of it honestly. Let me know what you think
> > ```python
> > import cript
> > 
> > with cript.API(host=None, token=None) as api:
> >     # upload and get back an S3 file link
> >     uploaded_file_source: str = api.upload_file(absolute_file_path="C:\\users\\username\\onedrive\\desktop\\my_file.txt")
> > 
> >     # use S3 file link
> >     my_file = cript.File(source=uploaded_file_source, type="my file type")
> > 
> >     # continue with the rest as usual
> >     my_data_node = cript.Data(name="my data node", file=[my_file], type="my data type")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in the JSON it will have the file source written as
> > ```json
> > {
> >     "node": ["file"],
> >     "name": "my file name",
> >     "type": "my file type",
> >     "source": "https://aws.123456.s3.link.come",
> >     "extension": ".csv"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > Note: I think in the future we can also add relative file paths as well but I did not add it here because I've noticed in the past that `../../my_file.txt` is not from where the file is, but from where the program has been ran which introduces another complication, but I think eventually I think we can make it work.
> 
> I think we should capsulate that a little better for the user. The user should write something like this:
> 
> ```python
> import cript
> 
> with cript.API(host=None, token=None) as api:
>     my_file = cript.File(absolute_file_path="C:\\users\\username\\onedrive\\desktop\\my_file.txt", type="my file type")
> 
>     # continue with the rest as usual
>     my_data_node = cript.Data(name="my data node", file=[my_file], type="my data type")
> ```
> 
> And upon the first time the node is converted into json, we trigger a function within the file node. So we overload the `get_json` function of file like this.
> 
> ```python
> class File:
>    def get_json(self):
>        if self.absolute_file_path is not None: # File hasn't been uploaded
>                # upload and get back an S3 file link
>                api = _get_cached_global_api()
>                uploaded_file_source: str = api._upload_file(self.absolute_file_path)
>                # Error checking
>                self._json_attrs = replace(self._json_attrs, source = uploaded_file_source) # store the source for json serialization
>                self.absolute_file_path = None # Signal that file has been successfully uploaded
>        # Call parent `get_json` for actual serialization
>        return super().get_json(self) 
> ```
> 
> and set the `source` in `json_attr`. Should be pretty simple to do. And hides all the complications from the user. And this automatically keeps track to only do this once.

---

I think this can work and it could make the user's workflow a bit easier. I don't know too much about the `get_json` function though, so that I would refer to you

**Comment by nh916** [comment]
should this PR go into the `validate branch` or into `develop branch` directly?

**Comment by InnocentBug** [comment]
> should this PR go into the `validate branch` or into `develop branch` directly?

probably either is fine.
The tricky bit is testing this branch.

**Comment by nh916** [comment]
> > should this PR go into the `validate branch` or into `develop branch` directly?
> 
> probably either is fine. The tricky bit is testing this branch.

I fully agree, and there are a few complications with testing upload and download regardless.

upload writing tests will be tricky because we don't want to use infinite cloud storage

download functionality in general might be tricky because we have to allow users to explore the available files that they have access to

**Comment by nh916** [comment]
putting this PR into the [file upload and download pr](https://github.com/C-Accel-CRIPT/Python-SDK/pull/95)

**Comment by nh916** [comment]
putting this PR into the [file upload and download pr](https://github.com/C-Accel-CRIPT/Python-SDK/pull/95)

**Pull request closed without merging**
