### PR TITLE
upgraded trunk

### PR DESCRIPTION
**Pull request by nh916**
# Description

upgraded trunk linters that were outdated

## Checklist

- [ ] My name is on the list of contributors (`CONTRIBUTORS.md`) in the pull request source branch.
- [ ] I have updated the documentation to reflect my changes.

### CODE REVIEW

**Review by InnocentBug — DISMISSED** [review]

**Comment by InnocentBug** [comment]
This relies quite a bit on the hold the line feature of trunk.
It maybe that as we modify files, trunk flags more issues.

Just something to keep in mind before merging.

**Comment by nh916** [comment]
> This relies quite a bit on the hold the line feature of trunk. It maybe that as we modify files, trunk flags more issues.
> 
> Just something to keep in mind before merging.

you're saying I should not merge it yet?

**Comment by nh916** [comment]
> No you can merge it.
> 
> It's just that I typically run `./trunk fmt -all` and `./trunk check --all` over the code after an upgrade. That highlights all the changes that come with the upgrade.

I did not do either of those. Were you able to run those to be sure everything is good?

**Comment by nh916** [comment]
I think I may have messed up this git branch by updating it. I'm going to close this PR and open a new one for upgrading of trunk

**Comment by InnocentBug** [comment]
I can upgrade it.

**Comment by nh916** [comment]
> I can upgrade it.

Thank you so much! You're already ahead of the game!

**Pull request closed without merging**
