### PR TITLE
Release CRIPT Python SDK v2.1.0

### PR DESCRIPTION
**Pull request by nh916**
# Description
Python SDK is ready for release v2.1.0

## Changes
* delete
  * with documentation
  * with integration tests
* updated/upgraded documentation for every node
  * fixed some outdated code examples
  * fixed issues with attributes tables
  * fixed broken links
* update requirement packages
* upgraded error messages and better error handling for many requests
* added `bigsmiles` search to SDK
* fixed static type errors found with mypy
* added `CRIPT USA Availability` in documentation and repository
* refactored `cript.Material` attribute from `identifiers` to `identifier`
  * updated all tests and documentation along with it
* resolved `trunk cspell` spell check issues

## Notes
* CRIPT Python SDK 2.1.0 will be the last version that will support Python 3.7 as [Python 3.7 has reached end of life](https://devguide.python.org/versions/)
  * Please upgrade to Python 3.8 or higher.

## Credits
@InnocentBug

### CODE REVIEW

**Review by InnocentBug — APPROVED** [review]

**Comment by InnocentBug** [comment]
I think you will have to do this manually outside of Github.
Force push this branch as main.

**Comment by nh916** [comment]
I think for this release what I'll have to do for this release is

**Force Push Develop Onto Main**
```
git checkout develop
git push origin develop:main --force     # force push develop onto main
```

**Refresh Main From Repo**
```
git branch -d main   # delete the local main branch
git fetch origin     # fetch the latest branches from remote
git checkout main    # checkout the new main which is now the same as develop
```

This is because I made a mistake last time and `squash & merged` the PRs from develop into main instead of a regular merge.

I looked into merge strategies for each branch to see if we can disable `squash & merge` for main branch, but I don't think that feature exists yet, but a lot of people seem to want it though.

https://github.com/orgs/community/discussions/10809

---

After develop is force pushed onto main, I will go ahead and make an [announcement on the repo](https://github.com/C-Accel-CRIPT/Python-SDK/discussions/categories/announcements)
1. whoever that has a copy of the SDK to be sure to delete their local branch and pull it again
2. that the SDK has a new release out

**Comment by nh916** [comment]
out of an abundance of caution I am waiting for a PR approval before force pushing develop to main

**Review by InnocentBug — APPROVED** [review]
Something is a little odd.
It almost looks like this is competely new code.
Its more like as if we merge against a deleted branch.

Its hard to review, but it looks fine to me.

**Comment by nh916** [comment]
> Something is a little odd. It almost looks like this is competely new code. Its more like as if we merge against a deleted branch.
> 
> Its hard to review, but it looks fine to me.

yeah I agree, I saw the same thing. It was my mistake for doing `squash & merge`  between develop and main in the first release. I'll add that to our internal wiki to always do a regular merge between develop and main and never do a `squash and merge` because it'll create merge conflicts.

maybe it thinks that since it only has a single commit and doesn't have all of those they are different

**Comment by nh916** [comment]
since we are force pushing and it is a bit dangerous, I'll keep a fork backup of the SDK, that we can use just in case

**Pull request merged**
