### PR TITLE
added documentation for cript.utils

### PR DESCRIPTION
**Pull request by nh916**
# Description
set up documentation for utility functions of the CRIPT Python SDK

## Changes
* added `Utility Functions` documentation
    * added it to mkdocs.yaml
    * created an md file for it
* wrote docstrings for `load_nodes_from_json`

## Screenshot
image

### CODE REVIEW

**Comment by nh916** [comment]
@InnocentBug what are your thoughts on doing a schema validation of the node before converting it from JSON to Python node?

**Comment by nh916** [comment]
I think it may be a better idea to hold off on this for now until because we are working heavily on utils functions and there might be a lot of changes and updates that would make this outdated

**Comment by InnocentBug** [comment]
> @InnocentBug what are your thoughts on doing a schema validation of the node before converting it from JSON to Python node?

yeah, we should do that.

**Comment by nh916** [comment]
@InnocentBug wrote this a while back and I was thinking of holding off until later, but I'm thinking of just putting it into the `validate-branch` for now. Not sure if I should hold off or not.

I think if we keep putting things into the validate branch it might end up becoming giant and at the end create a log merge conflicts, but I am not sure if we should merge it into develop either because some of the serialization and deserialization code needs clean up. what are your thoughts?

**Comment by InnocentBug** [comment]
> @InnocentBug what are your thoughts on doing a schema validation of the node before converting it from JSON to Python node?

Would be great, but doesn't work.
A JSON from the backend does not conform with the schema.

**Review by InnocentBug — APPROVED** [review]

**Pull request merged**
