### PR TITLE
Cspell

### PR DESCRIPTION
**Pull request by InnocentBug**
# Description
Add cspell as a checker for trunk.

This should alert us for any misspelled word.
## Changes

```
./trunk check enable cspell
```

## Tests
automatically included in trunk check
## Notes
I haven't actually started to fix all the issues, so for now it fails.
We need to go through the code and fix all misspelling, or teach cspell the missing words.
## Checklist

- [x] My name is on the list of contributors (`CONTRIBUTORS.md`) in the pull request source branch.

### CODE REVIEW

**Comment by nh916** [comment]
Love this! This is such a great check for our code that easily make a big impact!

**Comment by nh916** [comment]
I approve of this, but it is currently in draft mode. I would approve it in PR form as well

**Comment by nh916** [comment]
@InnocentBug since it would be quick to just add the words that we are using like `bigsmiles` into it, I can just do that now and knock it out

**Comment by InnocentBug** [comment]
> I approve of this, but it is currently in draft mode. I would approve it in PR form as well

Yeah, I put in draft mode, because it makes test fail.
Feel free to knock it out.
As soon as test is passing, we can merge it.

**Review by nh916 — APPROVED** [review]

**Pull request merged**
