### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by nh916**
# Description

Added a page on reporting any security issues to CRIPT

### CODE REVIEW

**Review by InnocentBug — APPROVED** [review]
Looks fine to me, not sure if I am the best person to approve this though.

**Comment by nh916** [comment]
> Looks fine to me, not sure if I am the best person to approve this though.

no worries we have other approvers as well and they'll check too!

**Review by bearmit — COMMENTED** [review]
Why the table is commented out?

**Comment by nh916** [comment]
> Why the table is commented out?

Good question, because we currently do not have any version released so none of them are supported or unsupported, once we start releasing then we can update the table I'm thinking

**Review by bearmit — APPROVED** [review]

**Pull request merged**
