### PR TITLE
Slimming tests

### PR DESCRIPTION
**Pull request by nh916**
# Description
Having a lot of tests can be good, but having a lot will create maintenance harder, more timely, and overall more costly. This PR addresses that issue by removing tests that are unneeded, already being captured somewhere else, and overall duplicates. I think these tests can be removed without much disadvantage.

## Changed Test Files
* `Computation`
* `Computation Process`
* `Data`
* `Experiment`
* `Material`
* `Process`
* `Reference`

## Checklist

- [ ] My name is on the list of contributors (`CONTRIBUTORS.md`) in the pull request source branch.

### CODE REVIEW

**Comment by InnocentBug** [comment]
I don't know we don't need to close it yet.
Maybe we think about it a bit more?

**Comment by nh916** [comment]
> I don't know we don't need to close it yet. Maybe we think about it a bit more?

okie dokes, I am okay with that!

**Comment by nh916** [comment]
@InnocentBug I'm thinking of removing this PR  because I think we both like to keep both minimal and maximal tests

**Comment by InnocentBug** [comment]
ok, let's close it.

The merge hopefully takes some of this pain away.

**Pull request closed without merging**
