### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by nh916**
# Description

Created a basic Code of Conduct for the repository aided by GitHub to establish guidelines for contributors. The Code of Conduct promotes inclusivity, respectful communication, and prohibits harassment and discrimination.

### CODE REVIEW

**Comment by nh916** [comment]
the test failing is a known issue and has been addressed in other PR but those still have more work to be done until they are merged and then it is easily fixed

**Comment by InnocentBug** [comment]
This is for ardiana to review, not me, correct?

**Comment by nh916** [comment]
> This is for ardiana to review, not me, correct?

honestly its super simple Code of Conduct recommended by GitHub, so we could probably review it too, but I think I'm going to ask @Ardi028 to be safe. I think she knows the most about the legal sides of CRIPT.

**Review by InnocentBug — APPROVED** [review]

**Comment by nh916** [comment]
@InnocentBug I think it only sometimes deletes the branch after merging it in

**Pull request merged**
