### PR TITLE
changed conftest.py to get storage token from env variable

### PR DESCRIPTION
**Pull request by nh916**
# Description
changed conftest.py to get storage token from env variable

## Checklist

- [ ] My name is on the list of contributors (`CONTRIBUTORS.md`) in the pull request source branch.
- [ ] I have updated the documentation to reflect my changes.

### CODE REVIEW

**Review by InnocentBug — APPROVED** [review]

**Review by InnocentBug — CHANGES_REQUESTED** [review]
we need to export a storage token in the test scripts.

**Comment by nh916** [comment]
> we need to export a storage token in the test scripts.

yeah I saw the CI issue and submitted the fix for it

**Comment by nh916** [comment]
@InnocentBug  seems like it is still having issues, I'll tag you when it is fully passing all tests

**Comment by nh916** [comment]
I believe everything should be passing now

**Review by InnocentBug — APPROVED** [review]

**Pull request merged**
