### PR TITLE
Add iterators for UUID nodes

### PR DESCRIPTION
**Pull request by InnocentBug**
# Description
Add iterator capability for UUID nodes.

## Changes

UUID attributes are strictly strings now.

## Notes

Let's add some test to ensure iteration over nodes is dfs, and we need to tests this with a graph that contains cycles.

## Checklist

- [ x] My name is on the list of contributors (`CONTRIBUTORS.md`) in the pull request source branch.
- [ x] I have updated the documentation to reflect my changes.
- [ x] My code changes have been verified by automated tests and pass all relevant test scenarios.

### CODE REVIEW

**Comment by InnocentBug** [comment]
@duboyal please add tests to this as discussed.
Even if the tests don't work, no worries just add them anyways, and I can debug.

**Review by duboyal — APPROVED** [review]

**Comment by InnocentBug** [comment]
we can't merge it yet, since it is untested

**Comment by InnocentBug** [comment]
I think the tests show green now.

**Review by duboyal — DISMISSED** [review]

**Review by duboyal — APPROVED** [review]

**Pull request merged**
