### PR TITLE
Release 2.2.0

### PR DESCRIPTION
**Pull request by nh916**
# Description

CRIPT Python SDK release v2.2.0 because there have been many minor change/improvements to the SDK both internal and external.

### PR Template Changes
* removed `Tests` section
* added a section that states the developer tested their software and wrote appropriate tests for it

### CI Upgrades
* using Python 12 for CI jobs that require a single python version
* CI runs Python `3.8` and `3.12`

### Documentation
* added more sections to FAQ docs and fixed spelling errors
* all code examples have been correct and I included CI into it
  * added doctest to all code examples
* added wiki documentation link to README.md
* fixed any missing/broken controlled vocabulary links
* added `BaseNode`, `UUIDBaseNode`, and `PrimaryBaseNode` to documentation
  * in future releases, full documentation will be written for all the methods/functions/attributes of the base classes along with code examples with full doctest
* wrote documentation for `CRIPTDuplicateNameError` exception & improved error message

### Tests
* renamed integrate_nodes_helper to save_integration_node_helper
* reorganizing utility functions into test/utils/
* made `tests/` into a package to be easily imported in tests
* created `dynamic_material_data` fixture for tests
* testing `notes` attribute within all nodes
* made error documentation headings more standard
  * from `"How to Fix"` to `"Troubleshooting"`

### API Class
* refactored `get_s3_client` into a function in a aws_s3_utils.py file 
* wrote docs for `_prepare_host` so it is clearer for future maintenance

### Paginator
* improved paginator error if API returns anything other than HTTP 200

#### File Node
* requiring file extension for the node

#### Material node
* removed redundant Material name getter and setter

### General
* upgraded `requirements.txt`, `requirements_docs.txt`, `requirements_dev.txt`
* CRIPT Python SDK requires Python 3.8+ as [Python 3.7 has been depreciated](https://devguide.python.org/versions/)
* refactored `APIError` to be cleaner/more maintainable and gives better error
  * upgraded the documentation for it with `Steps to try:`
* removed previously unfinished `TODO` comments

### Feature
* wrote `API.delete_node_by_uuid(node_type, node_uuid)` with docs and tests
* ~wrote `cript.API.get_node_by_uuid(uuid)` with full docs and tests~
  * [reasoning](https://github.com/C-Accel-CRIPT/Python-SDK/pull/409) for removing this feature before releasing it
    * essentially it was not robust and will lead to breaking changes in the near future
* `load_nodes_from_json` works with both str and dict args, updated documentation for that
* added feature to get [expanded JSON without UUID](https://github.com/C-Accel-CRIPT/Python-SDK/pull/412)
  * wrote feature, wrote comments, documentation, type hinting, doctests, and unit tests
* wrote feature to [skip validation](https://github.com/C-Accel-CRIPT/Python-SDK/pull/411)
  * useful for when wanting to skip validations that slow the program down 

## Breaking Changes
The SDK will only work with Python 3.8 or higher as [3.7 has been depreciated](https://devguide.python.org/versions/)

## Acknowledgments 🎉
Big thanks to @InnocentBug for volunteering to help with the [CRIPT Python SDK](https://github.com/C-Accel-CRIPT/Python-SDK) since its inception and continuing to add features, improve the SDK, and provide valuable support.

### CODE REVIEW

**Comment by InnocentBug** [comment]
Can we double check that the automated doctest runs as expected:

image

After that I am happy to approve.
I assume you ran the integration tests locally.

**Comment by nh916** [comment]
> Doctest

where are you seeing this error?

I think this may have been an issue that was happening before this PR: https://github.com/C-Accel-CRIPT/Python-SDK/pull/400/commits/8b8c02a18ff45a4b4c59d316ff2a602f23e6b5b8#diff-ee69ed616853bef377a895f4f5c98f45386f3cf9553beaef9f1111670554a86cL354

I double checked it locally just now and I think it seems to be working fine, but double check and let me know

**Review by InnocentBug — APPROVED** [review]

**Comment by InnocentBug** [comment]
> double checked it locally just now and I think it seems to be working fine, but double check and let me know

this seems to be a temporary error in how github displays the logs

**Comment by nh916** [comment]
> > double checked it locally just now and I think it seems to be working fine, but double check and let me know
> 
> this seems to be a temporary error in how github displays the logs

yeah that makes sense, I ran the tests locally and they all passed and the doctests are passing beautifully on the CI as well! Very well done job overall to both of us!

**Pull request merged**
