### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by nh916**
# Description

## Checklist

- [ ] My name is on the list of contributors (`CONTRIBUTORS.md`) in the pull request source branch.
- [ ] I have updated the documentation to reflect my changes.

### CODE REVIEW

**Comment by nh916** [comment]
@InnocentBug not sure what is going on with the merges and files, there should only be like 2 changes with just the spelling stuff that you fixed

**Comment by InnocentBug** [comment]
Maybe rebase develop on main?

**Comment by nh916** [comment]
> Maybe rebase develop on main?

I do not know as much about rebase, so I am not sure if that would mess something up or not

**Comment by nh916** [comment]
@bearmit you are better with git than I am, what are your thoughts here?

**Comment by bearmit** [comment]
@nh916 @InnocentBug 
The issue probably came when you merged master into develop in the past (you did if I am not wrong). When you need to pick few hotfixes you did on master, you can try to cherry-pick the commits instead.
I never had to do this type of things (picking changes on master to add them to develop) but it should not be more than 1 commit I guess.

**Comment by nh916** [comment]
@bearmit I honestly am not sure what the best course of action is here, but I'm guessing rebase is probably better, but I would rather if we could maybe squash the commits and merge it onto it

If we fix the merge conflicts and merge, would it still have issues later?

**Comment by bearmit** [comment]
> If we fix the merge conflicts and merge, would it still have issues later?

Do you need help to rebase? I don't understand why you are hesitating.

**Comment by InnocentBug** [comment]
I think the issue was that the release merge from develop to main was a squashed merged. 
https://github.com/C-Accel-CRIPT/Python-SDK/commit/ad7bcbf35742bf8d68442f074cf7b69c47d4d171

and that makes the two branches separate ( they don’t share a history). 
and without the shared history all these commits are like unmerged. 

I think next time we need a regular merge. 

For now. 
Either we revert the squashed merge and merge regularly. 
or we rebase develop ( but that loses the detailed history)

**Comment by bearmit** [comment]
> I think the issue was that the release merge from develop to main was a squashed merged. [ad7bcbf](https://github.com/C-Accel-CRIPT/Python-SDK/commit/ad7bcbf35742bf8d68442f074cf7b69c47d4d171)
> 
> and that makes the two branches separate ( they don’t share a history). and without the shared history all these commits are like unmerged.
> 
> I think next time we need a regular merge.
> 
> For now. Either we revert the squashed merge and merge regularly. or we rebase develop ( but that loses the detailed history)

Ok, this makes sense.

**Comment by nh916** [comment]
@bearmit I also don't have the ability to resolve the conflicts between develop and main because I do not have elevated permissions, so I cannot do anything about it

**Comment by bearmit** [comment]
> @bearmit I also don't have the ability to resolve the conflicts between develop and main because I do not have elevated permissions, so I cannot do anything to fix the issue

I do not understand why you are in this situation. I encourage you to ask for more privileges with your manager. You are the main developer and should have the rights to perform this action on your own.
I prefer not to bypass my role and ping @Ardi028 .

**Comment by nh916** [comment]
> > @bearmit I also don't have the ability to resolve the conflicts between develop and main because I do not have elevated permissions, so I cannot do anything to fix the issue
> 
> I do not understand why you are in this situation. I encourage you to ask for more privileges with your manager. You are the main developer and should have the rights to perform this action on your own. I prefer not to bypass my role and ping @Ardi028 .

I have asked a few times and have not been granted access and I am unsure as to why

**Comment by nh916** [comment]
closing this in favor of new PR for a new release of v2.1.0

**Pull request closed without merging**
