### PR TITLE
Made optional attributes optional in setters type hinting

### PR DESCRIPTION
**Pull request by nh916**
# Description

## Checklist

- [ ] My name is on the list of contributors (`CONTRIBUTORS.md`) in the pull request source branch.
- [ ] I have updated the documentation to reflect my changes.

### CODE REVIEW

**Comment by nh916** [comment]
@InnocentBug what are your thoughts on this?

**Comment by nh916** [comment]
lists cannot be optional and instead the user must give an empty list to wipe that field. This must be communicated clearly in the documentation so the user is not left wondering

**Comment by InnocentBug** [comment]
> @InnocentBug what are your thoughts on this?

I think that is OK.
Not highest priority if you ask me though.

**Comment by InnocentBug** [comment]
> lists cannot be optional and instead the user must give an empty list to wipe that field. This must be communicated clearly in the documentation so the user is not left wondering

not entirely true.
we can handle this like in the constructors.
If a None gets passed in the the function (the optional part), we convert it after into an empty list.

**Comment by nh916** [comment]
implemented everything for this PR better in this [PR](https://github.com/C-Accel-CRIPT/Python-SDK/pull/280) and it is already merged, so closing this one

**Pull request closed without merging**
